name: "producer-consumer"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_net

  producer:
    build:
      context: ./producer
      dockerfile: ./docker/Dockerfile
    container_name: producer
    ports:
      - 3333:3333
    command: npm run dev
    networks:
      - rabbitmq_net
    depends_on:
      - rabbitmq

  consumer:
    build:
      context: ./consumer
      dockerfile: ./docker/Dockerfile
    container_name: consumer
    command: npm run dev
    networks:
      - rabbitmq_net
    depends_on:
      - rabbitmq

networks:
  rabbitmq_net:
    driver: bridge
