global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]
  - job_name: "producer"
    static_configs:
      - targets: ["producer:3333"]
  - job_name: "consumer"
    static_configs:
      - targets: ["consumer:3334"]